version: "2"
services:
  client:
    build: angular-client
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client:/app
      - /app/node_modules

  server:
    build: nest-server
    ports:
      - "3000:3000"
    volumes:
      - ./nest-server:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
